name: Run tests

on:
    push:
      branches:
        - dev
      paths-ignore:
        - '**.md'
    pull_request:
      branches: 
        - '*'
      paths-ignore:
        - '**.md'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    services:
            rabbitmq:
                image: rabbitmq:3.11.3-alpine
                ports:
                - 5672:5672
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
            go test -coverprofile cover.out ./... -race -timeout=10s
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: cover.out
          format: golang
