name: Run tests

on:
    push:
      branches:
        - dev
      paths-ignore:
        - '**.md'
    pull_request:
      branches: 
        - '*'
      paths-ignore:
        - '**.md'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Setup RabbitMQ container
        run: |
            docker run -d \
              --name rabbitmq \
              -p 5672:5672 \
              --health-cmd "rabbitmq-diagnostics status && rabbitmq-diagnostics check_local_alarms" \
              --health-interval 60s \
              --health-timeout 30s \
              --health-retries 10 \
              --memory-reservation 150m \
              --memory 300m \
              rabbitmq:3.11-alpine

            echo "Waiting for RabbitMQ healthcheck to finish."
            until [ "$(docker inspect -f {{.State.Health.Status}} rabbitmq)" == "healthy" ]; do sleep 0.5; done;
            echo "RabbitMQ is healthy!"

            # Set high resource watermarks to avoid getting blocked on alarms.
            docker exec rabbitmq rabbitmqctl set_vm_memory_high_watermark 1
            docker exec rabbitmq rabbitmqctl set_disk_free_limit 1073741824 # 1GiB

      - name: Run tests
        run: |
            cp .env.example .env
            go test -coverprofile cover.out ./... -race -v -timeout=30s

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: cover.out
          format: golang
