name: Run tests

on:
    workflow_dispatch:
    push:
      branches:
        - dev
      paths-ignore:
        - '**.md'
    pull_request:
      branches: 
        - '*'
      paths-ignore:
        - '**.md'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Setup RabbitMQ container
        run: |
            docker run -d \
              --name rabbitmq \
              -p 5672:5672 \
              -p 15672:15672 \
              --health-cmd "rabbitmq-diagnostics status && rabbitmq-diagnostics check_local_alarms" \
              --health-interval 10s \
              --health-timeout 10s \
              --health-retries 10 \
              --memory-reservation 150m \
              rabbitmq:3.11-management

            echo "Waiting for RabbitMQ healthcheck to finish."
            until [ "$(docker inspect -f {{.State.Health.Status}} rabbitmq)" == "healthy" ]; do sleep 0.5; done;
            echo "RabbitMQ is healthy!"
            
            docker exec rabbitmq rabbitmqctl set_log_level debug
            
            curl -o rabbitmqadmin "http://localhost:15672/cli/rabbitmqadmin"
            python3 rabbitmqadmin declare exchange name=my-new-exchange type=fanout
            python3 rabbitmqadmin declare queue name=my-new-queue durable=false
            python3 rabbitmqadmin publish exchange=my-new-exchange routing_key=test payload="hello, world"
            python3 rabbitmqadmin get queue=my-new-queue ackmode=ack_requeue_false

      - name: Run tests
        run: |
            cp .env.example .env
            go test -coverprofile cover.out ./... -race -v -timeout=30s
      
      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: krixlion

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: cover.out
          format: golang
